---
title: "Fairbnb"
output: html_document
date: "2023-12-01"
---
---
title: "NAkhtari_Midterm"
output:
  bookdown::html_document2:
    toc: true
    toc_float: true 
    code_folding: hide
date: "2023-10-10"
---
<style type="text/css">

body{ /* Normal  */
      font-size: 14px;
  }
td {  /* Table  */
  font-size: 10px;
}
h1.title {
  font-size: 38px;
  color: Black;
}
h1 { /* Header 1 */
  font-size: 28px;
  color: Black;
}
h2 { /* Header 2 */
    font-size: 22px;
  color: Black;

code.r{ /* Code block */
    font-size: 14px;
}
pre { /* Code block - determines code spacing between lines */
    font-size: 14px;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, include=FALSE, class.source = 'fold-show'}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidycensus)
library(sf)
library(stargazer)
library(spdep)
library(caret)
library(ckanr)
library(FNN)
library(kableExtra)
library(grid)
library(viridisLite)
library(viridis)
library(gridExtra)
library(jtools)
library(ggcorrplot) 
library(corrr)      
library(kableExtra)
library(jtools)     
library(ggstance) 
library(ggpubr)   
library(broom.mixed) 
options(scipen = 999)


root.dir = "https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/DATA/"

source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")

census_api_key("a6d692af505769f28e39a3ac16b7dcbacb1dad58", overwrite = TRUE)

palette5 <- c("#25CB10", "#5AB60C", "#8FA108",   "#C48C04", "#FA7800")

palette6 <- c("#25CB10", "#5AB60C", "grey40",   "grey40", "#FA7800")

theme_update(plot.title = element_text(hjust = 0.5))



```



## Test Header

asdsadasd

